project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - quarto/**
    
    
author:
  - name: Vagish Hemmige
    email: vagish.hemmige@gmail.com



website:
  site-url: https://vagishhemmige.github.io/USRDS-PDF-analysis-project
  repo-url: https://github.com/VagishHemmige/USRDS-PDF-analysis-project
  repo-actions: [edit, issue]
  title: "Analysis of USRDS-related papers"

  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home

      - section: Background
        contents:
          - href: quarto/background.qmd
            text: Clinical background
          - href: quarto/analysis_methods.qmd
            text: Description of analysis methods

      - section: Setup and helper functions
        contents:
          - href: quarto/setup.qmd
            text: Setup
          - href: quarto/functions.qmd
            text: Functions

      - section: Methods
        contents:
          - href: quarto/manual_data.qmd
            text: Analysis of manual data extraction
          - href: quarto/llm_analysis.qmd
            text: LLM data extraction
          - href: quarto/data_cleaning.qmd
            text: Data cleaning
          - href: quarto/llm_data.qmd
            text: LLM data analysis
            
        
      - section: Results
        contents:
          - href: quarto/final_selection_papers.qmd
            text: Final selection of papers
          - href: quarto/results_manual.qmd
            text: Results of manual extraction of data
          - href: quarto/results_LLM_full.qmd
            text: LLM analysis of full dataset
          - href: quarto/results_LLM_transplant.qmd
            text: Transplant LLM analysis



  page-navigation: true

custom-callout:
  Rcode:
    icon: true
    icon-symbol: "💻 "
    color: "pink"

filters:
- custom-callout

format:
  html:
    theme: cosmo
    css: styles.scss
    toc: true
    code-fold: true
    code-tools: true
    page-layout: full
    code-summary: "Click to show/hide R Code"
    lightbox: true
